[tasks.build]
run = """
  docker build -t hello-sandbox .
"""

[tasks.dev]
usage = """
  arg "<dir>" default="{{config_root}}" help="project folder to mount into the container"
  flag "--port -p <port>" help="host:container port mapping" var=#true
  flag "--as-root" help="run as root user instead of development user"
"""
run = """
  if [[ ! -d .claude ]]; then
    echo "⚠️ creating empty claude settings folder"
    mkdir .claude
  else
    echo "✅ using existing claude settings folder"
  fi

  if [[ ! -e .claude.json ]]; then
    echo "⚠️ creating empty claude settings json"
    echo "{}" > .claude.json
  else
    echo "✅ using existing claude settings json"
  fi
  
  eval "ports=($usage_port)"
  port_flags=""
  for p in "${ports[@]}"; do
    port_flags="$port_flags -p $p"
  done

  if [[ -n "$port_flags" ]]; then
    echo "ℹ️ binding ports: $(echo \"$port_flags\" | xargs)"
  fi

  dirname=$(basename $usage_dir)
  echo "ℹ️ mounting project directory: $dirname from $usage_dir"

  root_flag=""
  if [[ $usage_as_root == "true" ]]; then
    echo "🚨 running as root user!"
    root_flag="-u root"
  fi

  echo ""

  docker run -it \
    --rm \
    $port_flags \
    $root_flag \
    --mount type=bind,src=$usage_dir,dst=/home/developer/$dirname \
    --mount type=bind,src={{config_root}}/.claude,dst=/home/developer/.claude \
    --mount type=bind,src={{config_root}}/.claude.json,dst=/home/developer/.claude.json \
    hello-sandbox \
    bash
"""
